SCR_PlaceableEntitiesRegistry {
 m_sAddon "GlobalConflictsUnits"
 m_bExposed 1
 m_Prefabs {
  "{7337E8733B2A9B74}Prefabs/Vehicles/Helicopters/Mi8MT/Mi8MT_armed_gunship_HE_NVA.et"
  "{3F27CF86235E1B0B}Prefabs/Vehicles/Helicopters/Mi8MT/Mi8MT_armed_NVA.et"
  "{466DA56F8591A722}Prefabs/Vehicles/Helicopters/Mi8MT/Mi8MT_unarmed_transport_NVA.et"
  "{DFDBF4245B246A6D}Prefabs/Vehicles/Helicopters/Mi8MT/Mi8MT_CDF_armed.et"
  "{EFE8BCA33D30B2A0}Prefabs/Vehicles/Helicopters/Mi8MT/Mi8MT_CDF_armed_rockets.et"
  "{83FC98FFD5D48825}Prefabs/Vehicles/Tracked/T-72A/T72A_NVA.et"
  "{EC4811AC7C17DC7E}Prefabs/Vehicles/Wheeled/BRDM2/BRDM2_NVA.et"
  "{1C1038CF07EA4B00}Prefabs/Vehicles/Wheeled/BTR70/NVA/BTR70_NVA.et"
  "{588D169A6DDB5AE6}Prefabs/Vehicles/Wheeled/UAZ452/UAZ452_ambulance_NVA.et"
  "{5F8882699C54858C}Prefabs/Vehicles/Wheeled/UAZ469/UAZ469_NVA.et"
  "{080A52884164EDB5}Prefabs/Vehicles/Wheeled/M998/CRX_M1025_armed_KORD_gunshield.et"
  "{E7264F33A0128CE6}Prefabs/Vehicles/Wheeled/M998/CRX_M1025_armed_KORD_gunshield_GPK.et"
  "{6B0E98CE6921FCC2}Prefabs/Vehicles/Wheeled/M998/CRX_M1025_armed_M2HB_gunshield.et"
  "{AEA02B023BB4500A}Prefabs/Vehicles/Wheeled/M998/CRX_M1025_armed_M2HB_gunshield_GPK.et"
  "{41033FD6FEC127E4}Prefabs/Vehicles/Wheeled/M998/CRX_M1025_armed_MK19_gunshield.et"
  "{AEFE6A346B76A191}Prefabs/Vehicles/Wheeled/M998/CRX_M1025_armed_MK19_gunshield_GPK.et"
  "{3085BE631A0DDBDE}Prefabs/Vehicles/Wheeled/M998/M1025_armed_BGM-71.et"
  "{2CE3925D1803A664}Prefabs/Vehicles/Wheeled/M998/M1025_armed_BGM-71_MERDC.et"
  "{27D3611557F5B1E4}Prefabs/Vehicles/Wheeled/M998/CRX_M1025_armed_KORD_gunshield_DESERT.et"
  "{CFBB670022F73A66}Prefabs/Vehicles/Wheeled/M998/CRX_M1025_armed_KORD_gunshield_DESERT_GPK.et"
  "{C00B26E6C8808EF8}Prefabs/Vehicles/Wheeled/M998/CRX_M1025_armed_M2HB_gunshield_DESERT.et"
  "{FB0BF44A4D6B98BC}Prefabs/Vehicles/Wheeled/M998/CRX_M1025_armed_M2HB_gunshield_DESERT_GPK.et"
  "{8CE4011B6B6BDAD7}Prefabs/Vehicles/Wheeled/M998/CRX_M1025_armed_MK19_gunshield_DESERT.et"
  "{E716D5D244C96141}Prefabs/Vehicles/Wheeled/M998/CRX_M1025_armed_MK19_gunshield_DESERT_GPK.et"
 }
}