SCR_Faction : "{B122E3B10BB3404B}Configs/Factions/OPFOR.conf" {
 FactionKey "GC_DRA"
 FactionColor 0.2961 0.0113 0.0011 1
 UIInfo SCR_FactionUIInfo "{68FCDB0FC58ED2D3}" {
  Name "DRA"
  Description "Democratic Republic of Afghanistan"
  Icon "{AD1ED9855B2AC96F}Images/Faction_Flags/DRA.edds"
  m_sNameUpper "DRA"
 }
 "Identity of soldiers" FactionIdentity "{6738D0373DCD2AA1}" : "{024218D2C7AFC638}Configs/Identities/FactionIdentity_Afghan.conf" {
 }
 "Radio encryption key" "DRA"
 m_iOrder 1001
 m_OutlineFactionColor 0.296 0.011 0.001 1
 m_NotificationFactionColor 0.296 0.011 0.001 1
 m_NotificationTextFactionColor 0.296 0.011 0.001 1
 m_bIsPlayable 0
 m_sFactionFlag "{AD1ED9855B2AC96F}Images/Faction_Flags/DRA.edds"
 m_FactionFlagMaterial "{AF57088A44BFEEE3}Assets/Props/Fabric/Flags/Data/Flag_1_2_DRA.emat"
 m_FactionLabel FACTION_GC_DRA
 m_aFriendlyFactionsIds {
  "CIV"
  "USSR"
 }
 m_CallsignInfo SCR_FactionCallsignInfo "{68FCDB0FC58ED2DF}" {
  m_aCompanyNames {
   SCR_CallsignInfo "{68FCDB0FC58ED2C1}" {
    m_sCallsign "1 (Sarandoy)"
   }
   SCR_CallsignInfo "{68FCDB0FC58ED2C0}" {
    m_sCallsign "2 (Panj)"
   }
   SCR_CallsignInfo "{68FCDB0FC58ED2C3}" {
    m_sCallsign "3 (Qater)"
   }
   SCR_CallsignInfo "{68FCDB0FC58ED2C2}" {
    m_sCallsign "4 (Pooni)"
   }
   SCR_CallsignInfo "{68FCDB0FC58ED2C5}" {
    m_sCallsign "5 (Alagh)"
   }
   SCR_CallsignInfo "{68FCDB0FC58E4276}" {
    m_sCallsign "6 (Zabra)"
   }
   SCR_CallsignInfo "{68FCDB0FC58E4277}" {
    m_sCallsign "7 (Garbeh)"
   }
   SCR_CallsignInfo "{68FCDB0FC58E4274}" {
    m_sCallsign "8 (Khargosh)"
   }
   SCR_CallsignInfo "{68FCDB0FC58E4275}" {
    m_sCallsign "9 (Cpehmaster)"
   }
  }
  m_aPlatoonNames {
   SCR_CallsignInfo "{68FCDB0FC58E427A}" {
    m_sCallsign "1"
   }
   SCR_CallsignInfo "{68FCDB0FC58E427B}" {
    m_sCallsign "2"
   }
   SCR_CallsignInfo "{68FCDB0FC58E45AB}" {
    m_sCallsign "3"
   }
   SCR_CallsignInfo "{68FCDB0FC58E40FB}" {
    m_sCallsign "4"
   }
   SCR_CallsignInfo "{68FCDB0FC58E40F8}" {
    m_sCallsign "5"
   }
   SCR_CallsignInfo "{68FCDB0FC58E40F9}" {
    m_sCallsign "6"
   }
   SCR_CallsignInfo "{68FCDB0FC58E4974}" {
    m_sCallsign "7"
   }
   SCR_CallsignInfo "{68FCDB0FC58E4973}" {
    m_sCallsign "8"
   }
   SCR_CallsignInfo "{68FCDB0FC58E4972}" {
    m_sCallsign "9"
   }
  }
  m_aSquadNames {
   SCR_CallsignInfo "{68FCDB0FC58E4971}" {
    m_sCallsign "0"
   }
   SCR_CallsignInfo "{68FCDB0FC58E4970}" {
    m_sCallsign "1 HQ"
   }
   SCR_CallsignInfo "{68FCDB0FC5F1F096}" {
    m_sCallsign "1"
   }
   SCR_CallsignInfo "{68FCDB0FC5F1F089}" {
    m_sCallsign "2"
   }
   SCR_CallsignInfo "{68FCDB0FC5F1F081}" {
    m_sCallsign "3"
   }
   SCR_CallsignInfo "{68FCDB0FC5F13CB2}" {
    m_sCallsign "4 HQ"
   }
   SCR_CallsignInfo "{68FCDB0FC5F13CB3}" {
    m_sCallsign "4"
   }
   SCR_CallsignInfo "{68FCDB0FC5F13CB0}" {
    m_sCallsign "5"
   }
   SCR_CallsignInfo "{68FCDB0FC5F13CB1}" {
    m_sCallsign "6"
   }
   SCR_CallsignInfo "{68FCDB0FC5F16B2A}" {
    m_sCallsign "7 HQ"
   }
   SCR_CallsignInfo "{68FCDB0FC5F16B2C}" {
    m_sCallsign "7"
   }
   SCR_CallsignInfo "{68FCDB0FC5F15927}" {
    m_sCallsign "8"
   }
   SCR_CallsignInfo "{68FCDB0FC5F15924}" {
    m_sCallsign "9"
   }
  }
  m_sCallsignGroupFormat "%1 %2%3"
  m_sCallsignCharacterFormat "%1-%2%3%4"
  m_sCallsignCharacterWithRoleFormat "%1-%2%3 %4"
  m_aCharacterRoleCallsigns {
   SCR_PlayerLeaderRoleCallsign "{68FCDB0FC5F1595A}" {
   }
  }
 }
 m_FactionHomeTerritoryConfig SCR_FactionHomeTerritoryConfig "{68FCDB0FC5F15958}" {
 }
 m_rMapPrefab "{F849217AB3BA88BE}Prefabs/Items/Equipment/Maps/Map_Paper_01/PaperMap_01_folded_USSR.et"
}